#访问端口号
server:
  port: 8081

spring:
#  设置环境
#  profiles:
#    active: dev
# 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 阿里云数据库
    url: jdbc:mysql://cc0305.mysql.polardb.rds.aliyuncs.com:3306/cc?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: cc
    password: Bin552929
    # 本地数据库
#    url: jdbc:mysql://localhost:3306/cc?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: root
# redis连接信息
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 500
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
# 配置静态资源的处理以及文件上传参数
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/static/
  config:
    location: classpath:/application.yml
aliyun:
  oss:
    # oss对外服务的访问域名
    endpoint: oss-cn-guangzhou.aliyuncs.com
    # 访问身份验证中用到用户标识
    accessKeyId: LTAI5tH5TkkaxYDWBxu1KhSn
    # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    accessKeySecret: ufWbTLe7VlihWYfU1gop6wL1Hr2c2U
    # oss的存储空间
    bucketName: postfiles
    # 上传文件大小(M)


## 自定义用户凭证---
#  security:
#    user:
#      name: admin
#      password: admin
# 上传图片路径到本地
upload:
  path: src/main/resources/static/
# 添加图片到数据库，访问地址
addSysImgToDB:
  path: static/sys_img/

#关闭spring日志
#  main:
#    banner-mode: off
#debug warn

# mapper打印日志
logging:
  level:
    com.example.ccbackend.user.mapper: debug

#  实体类匹配数据库表列名驼峰命名
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  1、设置mapper.xml返回值类型的别名---2、mapper.xml位置
  type-aliases-package: cc.backend.entity
  mapper-locations: classpath:mapper/user/*.xml,classpath:mapper/manager/*.xml

# MP日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 全局配置雪花算法为id赋值
  global-config:
    banner: false
    db-config:
      id-type: assign_id
#      为字段名deleted操作为逻辑删除
      logic-delete-field: deleted
      logic-not-delete-value: 1
      logic-delete-value: 0
#  1、设置mapper.xml返回值类型的别名---2、mapper.xml位置
  type-aliases-package: cc.backend.entity
  mapper-locations: classpath:mapper/user/*.xml,classpath:mapper/manager/*.xml

















#---
##开发
#spring:
#  profiles: dev
#server:
#  port: 80
#---
## test
#spring:
#  profiles: test
#server:
#  port: 81
#---
## 上线
#spring:
#  profiles: pro
#server:
#  port: 82
#---